/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/blackalex1/sentinel-core/cmd/cshared */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* SentinelBuildConfig(char* specJSON);
extern char* SentinelBuildServerConfig(char* specJSON);
extern char* SentinelParseURI(char* rawURI);
extern char* SentinelGenerateURI(char* profileJSON);
extern char* SentinelGenerateX25519Keys(void);
extern char* SentinelGenerateVlessEncKeys(void);
extern char* SentinelGetCoresStatus(void);
extern char* SentinelRegisterHysteriaPort(int port);
extern char* SentinelConfigureSupervisor(char* configJSON);
extern char* SentinelGetUnifiedTraffic(void);
extern char* SentinelKickClient(char* clientEmail);
extern char* SentinelGetCoreLogs(char* logPath, int maxLines);
extern char* SentinelPing(char* host, int port, int timeoutMs);
extern char* SentinelEncrypt(char* data, char* secret);
extern char* SentinelDecrypt(char* payload, char* secret);
extern char* SentinelListPresets(void);
extern char* SentinelGetPreset(char* presetID);
extern char* SentinelGetConfigurationSchema(char* lang);
extern char* SentinelEncryptPayload(char* plaintext, char* secret);
extern char* SentinelDecryptPayload(char* ciphertext, char* secret);
extern char* SentinelRunHealthCheck(int socksPort, int httpPort, char* secret);
extern char* SentinelStartCore(char* core, char* bin, char* config);
extern char* SentinelStopCore(char* core);
extern char* SentinelRestartCore(char* core, char* bin, char* config);
extern char* SentinelValidateCore(char* core, char* bin, char* config);
extern char* SentinelGetCoreVersion(char* core, char* bin);
extern char* SentinelPopLogLine(char* core, int timeoutMs);
extern char* SentinelGetInMemoryLogs(char* core, int limit);
extern char* SentinelClearInMemoryLogs(char* core);
extern char* SentinelGetSecuritySchema(char* lang);
extern char* SentinelGetDefaultSecurityConfig(void);
extern char* SentinelValidateSecurityConfig(char* configJSON);
extern char* SentinelAndroidAuditConnection(char* reqJSON);
extern char* SentinelAndroidWritePcap(char* filePath, char* rawHex, long long int timestampMs);
extern char* SentinelAndroidSynthesizeAndWritePcap(char* filePath, char* proto, char* srcIP, int srcPort, char* dstIP, int dstPort, int tcpFlags, unsigned int seq, unsigned int ack, int window, char* payloadHex, long long int timestampMs);
extern char* SentinelAndroidDissectPacket(char* rawHex);
extern char* SentinelAndroidBlockApp(char* pkgName);
extern char* SentinelAndroidUnblockApp(char* pkgName);
extern char* SentinelAndroidIsAppBlocked(char* pkgName);
extern char* SentinelAndroidGetBlockedApps(void);
extern char* SentinelAndroidClearThreats(void);
extern void SentinelFreeString(char* str);

#ifdef __cplusplus
}
#endif
